"""Add email and username indexes to user table

Revision ID: a14bba9575ca
Revises: 10b05f409503
Create Date: 2024-07-25 10:45:47.957112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14bba9575ca'
down_revision: Union[str, None] = '10b05f409503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_email_index', 'user', ['email'], unique=False)
    op.create_index('user_username_index', 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_username_index', table_name='user')
    op.drop_index('user_email_index', table_name='user')
    # ### end Alembic commands ###
